TyrianTyrell/PampieStationRecoded

- _maps/shuttles/arrival_box.dmm
- _maps/shuttles/arrival_delta.dmm
:cl:
add: Added like, all the accessibility
/:cl:
> about 300% more accessibility for the two arrival shuttles.

- code/game/objects/items/RSF.dm
- code/game/objects/items/robot/robot_items.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
You can guess what this does, right? Yeah probably.
Pacifiers will be added when they're added.
:cl:
add: Added a Rapid Nursery Dispenser
tweak: Expanded medical cyborg gripper interaction protocols
/:cl:
> Nanny Functionality for Med-Borgs.

- code/game/objects/items/robot/robot_items.dm
This is usually why used and unused diapers should have the same general path but eh, guess this will do.
:cl:
add: It will have to do!
/:cl:
> The borgs should be able to trash diapers after changing too.

- code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
It's easy enough to do and works.
Bap
:cl:
adds: bap.
/:cl:
> Adds a recipe for the newspaper baton

- code/modules/language/arachnid.dm
- code/modules/language/babybabble.dm
- code/modules/language/draconic.dm
- code/modules/language/monkey.dm
- code/modules/language/voltaic.dm
> More Animalbased languages. For that Fennec Screaming of Angel.

- code/__DEFINES/traits.dm
- code/datums/brain_damage/severe.dm
- code/datums/traits/negative.dm
- code/modules/vehicles/motorized_wheelchair.dm
> Adds Deafness and Quadriplegia

- code/modules/incon/items.dm
> Adds Miasma Generation

- code/modules/incon/items.dm
- code/modules/mob/living/carbon/human/species_types/anthropomorph.dm
- code/modules/mob/living/carbon/human/species_types/ipc.dm
- code/modules/mob/living/carbon/human/species_types/synthliz.dm
> Synthetic Balance and Miasma containing.

- code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
- code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
- code/game/objects/structures/crates_lockers/closets/secure/security.dm
- code/modules/mining/machine_vending.dm
- code/modules/surgery/organs/autosurgeon.dm
Adding autosurgeons corresponding to the departments, based on the CMO's
:cl:
add: Autosurgeons for Heads and Miners
/:cl:
> Department Head Autosurgeons

- code/modules/mining/machine_vending.dm
> Commas save lives

- code/__DEFINES/DNA.dm
- code/datums/mutations/body.dm
- code/datums/mutations/combined.dm
- code/modules/client/client_procs.dm
- code/modules/mining/lavaland/necropolis_chests.dm
:cl:
tweak: Everyone can be an angel now.
fix: fixed mutations not working...
remove: ...by removing them.
admin: Upload limit is now higher.
/:cl:
> Some Misc fixes, including custom sounds, angels and removing the not-working mutations

- code/__HELPERS/_cit_helpers.dm
- code/__HELPERS/global_lists.dm
- code/modules/client/preferences.dm
:cl:
add: Added milk selection
/:cl:
> Pickable Milk (Test this please! I can't compile, windows update broke it)

- code/__DEFINES/radiation.dm
- code/modules/mob/living/carbon/monkey/life.dm
> Anti Gorilla Propaganda

- code/modules/food_and_drinks/drinks/drinks/bottle.dm
- code/modules/incon/diapvending.dm
- code/modules/reagents/reagent_containers/glass.dm
- code/modules/research/designs/misc_designs.dm
- code/modules/research/techweb/nodes/export_nodes.dm
> working on fixing bottles

- code/__DEFINES/citadel_defines.dm
- code/__DEFINES/traits.dm
- code/datums/diseases/advance/presets.dm
- code/datums/traits/neutral.dm
- code/modules/cargo/packs/medical.dm
- code/modules/client/preferences.dm
- code/modules/events/disease_outbreak.dm
- code/modules/events/shuttle_loan.dm
- code/modules/incon/items.dm
- code/modules/incon/reagents.dm
- code/modules/incon/regressoray.dm
- code/modules/reagents/reagent_containers/bottle.dm
> Lupus, Prefs, Changes

- _maps/RandomRuins/LavaRuins/lavaland_surface_library.dmm
- _maps/RandomRuins/LavaRuins/lavaland_surface_mining_site.dmm
> Oh yeah, Space tiles in lavaland are bad.

- code/datums/traits/negative.dm
- code/modules/antagonists/_common/antag_datum.dm
- code/modules/incon/diaperstatus.dm
- code/modules/jobs/job_types/captain.dm
- code/modules/jobs/job_types/chief_engineer.dm
- code/modules/jobs/job_types/chief_medical_officer.dm
- code/modules/jobs/job_types/detective.dm
- code/modules/jobs/job_types/head_of_personnel.dm
- code/modules/jobs/job_types/head_of_security.dm
- code/modules/jobs/job_types/quartermaster.dm
- code/modules/jobs/job_types/research_director.dm
- code/modules/jobs/job_types/security_officer.dm
- code/modules/jobs/job_types/warden.dm
Some of the new disabilities aren't blacklisted and some of the old ones have antag removal texts but aren't removed by antagging which is weird.
:cl:
/:cl:
> Blacklisting more traits

- code/modules/hydroponics/grown/marshmallows.dm
- code/modules/incon/reagents.dm
> should fix invisible plants and infinite harvests.

- code/datums/status_effects/debuffs.dm
- code/modules/antagonists/changeling/powers/tiny_prick.dm
- code/modules/mining/equipment/kinetic_crusher.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
- code/modules/uplink/uplink_items/uplink_roles.dm
:cl:
add: A variety of features for miners to punch people and NPCs.
add: Misc Changeling things.
fix: Oh yeah, GPS for BDM is back
/:cl:
> Assorted Changes

- code/datums/brain_damage/severe.dm
> forgot to fix this bit

- code/controllers/subsystem/traumas.dm
- code/datums/brain_damage/phobia.dm
- strings/phobia.json
Adds a new phobia option: fear of toilets.
It's funny and appropriate for our server. uwu
:cl:
add: Players can now roll a fear of the toilet
/:cl:
> New possible phobia. uwu

- _maps/shuttles/emergency_bathroom.dmm
- code/datums/shuttles.dm
- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
- modular_citadel/code/modules/reagents/chemistry/reagents/MKUltra.dm
- modular_citadel/code/modules/reagents/chemistry/reagents/SDGF.dm
- modular_citadel/code/modules/reagents/chemistry/reagents/eigentstasium.dm
- modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm
- modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
- modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm
Adds a new escape shuttle in the form of the Emergency Bathroom.
Also ports upstream PR 15478
A new, thematic shuttle for the players to make use of, and some consistency adjustments to chemical descriptions
:cl:
add: Added the Emergency Bathroom escape shuttle
tweak: Added or adjusted the taste descriptions of some chemicals
spellcheck: Removed some instances of double punctuation from chemical taste descriptions.
/:cl:
> Introducing: The Emergency Bathroom

- code/game/objects/items/stacks/sheets/sheet_types.dm
Commented out the lines that allow crafting the Crib and Highchair
It allows the damn game to be able to compile
> The Problem File

- _maps/RandomZLevels/away_mission/daycare.dmm
- _maps/map_files/BoxStation/BoxStation.dmm
Adds Maelstrom's creations to BoxStation. Kilo will get them too after that PR has been merged. :>
Will wait to add them to the other maps, for now.
Allows our players to engage with Mael's hard work without having to manually build them somewhere random (but still lets them do so if they please!).
:cl:
add: There are now highchairs and cribs in BoxStation
/:cl:
> Mapping in our new furniture

- code/modules/events/spontaneous_disability.dm
- tgstation.dme
It's Disability pride month! Let's Celebrate! Here's an Event.
A sense of community is always good
:cl:
add: a new random event to give people something to be proud about
/:cl:
> Disability pride Month!

- tools/build/build.sh
The way it compiled before was using Monsternos and putnam gave me the fix which is katmos, it compiles it to load everything properly
:cl:
/:cl:
> Auxmos compilation errors fixed

- code/datums/components/storage/concrete/pockets.dm
- code/modules/clothing/gloves/miscellaneous.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/incon/diapvending.dm
Added locking variants of Mittens and Booties
Ensures little ones stay out of trouble
:cl:
add: Locking Mittens and it's Key
add: Locking Booties and it's Key
/:cl:
> locks and keys

- code/datums/components/storage/concrete/pockets.dm
- code/modules/clothing/gloves/miscellaneous.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/incon/diapvending.dm
Fixed a bug that prevented buying pink locking booties from wall diaper vender
fixed a bug
Tweaked: unified Mitten and Bootie key
Fixed: Pink Mitten not appearing in wall vender
> percussive maintenance on the diaper vender

- code/modules/events/cat_surgeon.dm
- code/modules/events/spontaneous_disability.dm
> Event Rebalance.
